### ISSUE TITLE
GH_LOGIN is null, causing multiple comments on the same PR

### ISSUE THREAD

**Issue by tuncaulubilge** [benjlevesque/circleci-orbs#7]
Such a simple and helpful orb @benjlevesque, thanks for the great work!

I've noticed a small issue in the way you fetch the login info. You are currently using `user/repos` endpoint but then it fails to grab the username via jq. Since the GH_LOGIN fails, then the check for `maxComments` also fails. This can be remedied by using `user` endpoint instead of repos.

```
GH_LOGIN=$(curl -sS -H 'Authorization: token $GHI_TOKEN' https://api.github.com/user | jq '.login' --raw-output)
```

**Comment by benjlevesque** [comment]
👍
